version: '3.8'

services:
    mysql:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: $MYSQL_DATABASE
            MYSQL_USER: $MYSQL_USER
            MYSQL_PASSWORD: $MYSQL_PASSWORD
        ports:
            - 3306:$MYSQL_PORT
        volumes:
            - mysql_data:/var/lib/mysql
    redis:
        image: redis:latest
        ports:
            - 6379:$REDIS_PORT
        volumes:
            - redis_data:/data
volumes:
    mysql_data:
    redis_data:
